
'use client';

// This file is automatically generated. Do not modify it manually.
import { useState, useEffect, useRef } from 'react';
import {
  collection,
  query,
  onSnapshot,
  type DocumentData,
  type CollectionReference,
  type Query,
} from 'firebase/firestore';
import { useFirestore } from '../provider';
import { errorEmitter } from '../error-emitter';
import { FirestorePermissionError } from '../errors';

export function useCollection<T>(path: string, options?: {
  where?: [string, '==', any];
}) {
  const firestore = useFirestore();
  const [data, setData] = useState<T[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const queryRef = useRef<Query | CollectionReference | null>(null);

  useEffect(() => {
    if (!firestore) return;

    try {
      if (options?.where) {
        const [field, op, value] = options.where;
        queryRef.current = query(collection(firestore, path), where(field, op, value));
      } else {
        queryRef.current = collection(firestore, path);
      }

      const unsubscribe = onSnapshot(queryRef.current, (snapshot) => {
        const docs = snapshot.docs.map(doc => ({ ...doc.data() as T, id: doc.id }));
        setData(docs);
        setLoading(false);
      }, (err) => {
        console.error(err);
        const permissionError = new FirestorePermissionError({
          path,
          operation: 'list',
        });
        errorEmitter.emit('permission-error', permissionError);
        setError(permissionError);
        setLoading(false);
      });

      return () => unsubscribe();
    } catch (e: any) {
      setError(e);
      setLoading(false);
    }
  }, [firestore, path, options?.where]);

  return { data, loading, error };
}
