'use client';

// This file is automatically generated. Do not modify it manually.
import { useState, useEffect, useRef } from 'react';
import { doc, onSnapshot, type DocumentReference } from 'firebase/firestore';
import { useFirestore } from '../provider';
import { errorEmitter } from '../error-emitter';
import { FirestorePermissionError } from '../errors';

type UseDocResult<T> = {
  data: (T & { id: string }) | null;
  loading: boolean;
  error: Error | null;
};

export function useDoc<T>(path: string | null | undefined): UseDocResult<T> {
  const firestore = useFirestore();

  const [data, setData] = useState<(T & { id: string }) | null>(null);
  const [loading, setLoading] = useState<boolean>(!!path);
  const [error, setError] = useState<Error | null>(null);

  const docRef = useRef<DocumentReference | null>(null);

  useEffect(() => {
    if (!firestore) return;

    // ✅ Allow caller to "skip" the subscription
    if (!path) {
      docRef.current = null;
      setData(null);
      setError(null);
      setLoading(false);
      return;
    }

    // Reset state when path changes
    setLoading(true);
    setError(null);

    try {
      docRef.current = doc(firestore, path);

      const unsubscribe = onSnapshot(
        docRef.current,
        (snapshot) => {
          if (snapshot.exists()) {
            setData({ ...(snapshot.data() as T), id: snapshot.id });
          } else {
            setData(null);
          }
          setLoading(false);
        },
        (err) => {
          console.error(err);

          const permissionError = new FirestorePermissionError({
            path,
            operation: 'get',
          });

          errorEmitter.emit('permission-error', permissionError);
          setError(permissionError);
          setLoading(false);
        }
      );

      return () => unsubscribe();
    } catch (e: any) {
      setError(e);
      setLoading(false);
    }
  }, [firestore, path]);

  return { data, loading, error };
}
