
'use client';

// This file is automatically generated. Do not modify it manually.
import { useState, useEffect, useRef } from 'react';
import { doc, onSnapshot, type DocumentData, type DocumentReference } from 'firebase/firestore';
import { useFirestore } from '../provider';
import { errorEmitter } from '../error-emitter';
import { FirestorePermissionError } from '../errors';

export function useDoc<T>(path: string) {
  const firestore = useFirestore();
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const docRef = useRef<DocumentReference | null>(null);

  useEffect(() => {
    if (!firestore) return;

    try {
      docRef.current = doc(firestore, path);
      const unsubscribe = onSnapshot(docRef.current, (snapshot) => {
        if (snapshot.exists()) {
          setData({ ...snapshot.data() as T, id: snapshot.id });
        } else {
          setData(null);
        }
        setLoading(false);
      }, (err) => {
        console.error(err);
        const permissionError = new FirestorePermissionError({
          path,
          operation: 'get',
        });
        errorEmitter.emit('permission-error', permissionError);
        setError(permissionError);
        setLoading(false);
      });

      return () => unsubscribe();
    } catch (e: any) {
      setError(e);
      setLoading(false);
    }
  }, [firestore, path]);

  return { data, loading, error };
}
