
'use client';

// This file is automatically generated. Do not modify it manually.
import { FirebaseProvider } from './provider';
import { initializeFirebase } from '.';
import type { ReactNode } from 'react';
import { FirebaseErrorListener } from '@/components/FirebaseErrorListener';

export function FirebaseClientProvider({ children }: { children: ReactNode }) {
  const { firebaseApp, auth, firestore } = initializeFirebase();
  return (
    <FirebaseProvider
      firebaseApp={firebaseApp}
      auth={auth}
      firestore={firestore}
    >
      {children}
      <FirebaseErrorListener />
    </FirebaseProvider>
  );
}
