
// This file is automatically generated. Do not modify it manually.
// Your web app's Firebase configuration
export const firebaseConfig = {
  apiKey: "AIzaSyB1oBVt9iWXH7w3diIOs1ysOOWGzCbPKtE",
  authDomain: "lweemee-f4c1c.firebaseapp.com",
  projectId: "lweemee-f4c1c",
  storageBucket: "lweemee-f4c1c.appspot.com",
  messagingSenderId: "299622000598",
  appId: "1:299622000598:web:cbd13b58458b4374946677",
};
