
// This file is automatically generated. Do not modify it manually.
export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  requestResourceData?: any;
};

export class FirestorePermissionError extends Error {
  constructor(public context: SecurityRuleContext) {
    super(`Firestore Permission Denied: ${context.operation} on ${context.path}`);
    this.name = 'FirestorePermissionError';
  }
}
